import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { config } from "@fortawesome/fontawesome-svg-core";
import { NextFont } from "next/dist/compiled/@next/font";

import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "react-datepicker/dist/react-datepicker.css";

config.autoAddCss = false;

const inter: NextFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
